### ISSUE TITLE
Notice quand pas de défense

### ISSUE THREAD

**Issue by xtero** [Gritch69/XG-Proyect-v3.x.x#5]
Quand on arrive pour construire sa première défense, on a les messages suivants qui apparaissent.
```
 Notice: Undefined offset: 0 in /var/www/html/application/libraries/DevelopmentsLib.php on line 265

Notice: Undefined offset: 0 in /var/www/html/application/libraries/DevelopmentsLib.php on line 266

Notice: Undefined index: in /var/www/html/application/libraries/DevelopmentsLib.php on line 266

Notice: Undefined variable: time in /var/www/html/application/libraries/DevelopmentsLib.php on line 314

Notice: Undefined offset: 1 in /var/www/html/application/controllers/game/defense.php on line 325

Notice: Undefined offset: 1 in /var/www/html/application/controllers/game/defense.php on line 328
```

**Comment by xtero** [comment]
Probablement lié à https://github.com/Gritch69/XG-Proyect-v3.x.x/issues/4

**Comment by Clem69B** [comment]
Je pense que c'est deux chose différentes. L'un est lié à l'affichage de la
page, l'autre correspond à un problème dans la lib d'update.

**Comment by xtero** [comment]
J'ai le même problème sur la page pour construire des vaisseaux.
Vue que c'est le même code appele, je pense que c'est le meme problème.

De plus, je n'ai pas la possibiblié de lancer la production de defense ou de vaisseaux.
